name:  Job - Server Test (small size)

on:
  workflow_call:
    inputs:
      with-coverage:
        required: false
        type: boolean
        default: false
        description: 'Whether to generate coverage report'

jobs:
  test:
    name: Run Small Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'
          cache: true

      - name: Install oapi-codegen
        run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Install sqlc
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Generate code
        run: make generate

      - name: Verify dependencies
        run: go mod verify

      - name: Run small tests
        if: ${{ !inputs.with-coverage }}
        run: go test -tags=small ./...

      - name: Run small tests with coverage
        if: ${{ inputs.with-coverage }}
        run: |
          COVERAGE=$(cat scripts/coverage.txt)
          go test -tags=small -race -coverprofile=coverage.txt -covermode=atomic $COVERAGE

      - name: Upload coverage report
        if: ${{ inputs.with-coverage }}
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: server/coverage.txt