name: On Push(Web)

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
  workflow_dispatch:

concurrency:
  group: web-deploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  job-web-deploy:
    uses: ./.github/workflows/job-web-deploy.yml
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      APP_API_URL: ${{ secrets.APP_API_URL }}
