name: On Pull Request(Web)

on:
  pull_request:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  lint:
    uses: ./.github/workflows/job-web-lint.yml

  build:
    uses: ./.github/workflows/job-web-build.yml

  test-small:
    needs:
      - lint
      - build
    uses: ./.github/workflows/job-web-test-small.yml
